import UsekaseNavbar from "@/components/layout/UsekaseNavbar";
import UsekaseFooter from "@/components/layout/UsekaseFooter";
import { motion } from "framer-motion";
import { FileText, Mail } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <UsekaseNavbar />

      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-12"
          >
            <div className="flex justify-center mb-6">
              <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center">
                <FileText className="h-8 w-8 text-primary" />
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4">
              Terms of <span className="text-primary">Service</span>
            </h1>
            <p className="text-lg text-muted-foreground">
              Effective Date: January 1st, 2025
            </p>
          </motion.div>

          {/* Content */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="prose prose-lg max-w-none prose-headings:font-bold prose-headings:text-foreground prose-p:text-muted-foreground prose-li:text-muted-foreground prose-strong:text-foreground"
          >
            <div className="bg-card border border-border rounded-lg p-6 md:p-8 lg:p-10 space-y-8">
              {/* Introduction */}
              <section>
                <p className="text-base leading-relaxed">
                  These Terms of Service govern your use of the website Usekase.ai and the services provided therein.
                </p>
              </section>

              {/* 1. General Provisions */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">1. General Provisions</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>1.1.</strong> These Terms of Service ("Terms") govern your use of the website playbook.Usekase.ai ("Usekase") and the services provided therein ("Services").
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>1.2.</strong> Usekase is managed and administered by
                  </p>
                  <p className="text-base leading-relaxed pl-6">
                    Usekase Pte Ltd, 57 Meyer Road, #01-07, 437878 Singapore ("Company").
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>1.3.</strong> By accessing or using Usekase in any manner, you ("User") agree to comply with these Terms. If you do not agree with any part of these Terms, you must not use Usekase.
                  </p>
                </div>
              </section>

              {/* 2. Definitions */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">2. Definitions</h2>
                <p className="text-base leading-relaxed mb-4">
                  <strong>2.1.</strong> For the purposes of these Terms:
                </p>
                <ul className="space-y-2 list-disc pl-6">
                  <li className="text-base"><strong>"Account":</strong> A User account created on Usekase to access Services.</li>
                  <li className="text-base"><strong>"Content":</strong> Information, data, text, graphics, or other materials provided through Usekase.</li>
                  <li className="text-base"><strong>"Report":</strong> A comprehensive insight report generated by Usekase based on publicly available information.</li>
                </ul>
              </section>

              {/* 3. User Accounts */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">3. User Accounts</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>3.1.</strong> To access certain Services, Users must create an Account by providing a valid email address and password or by using third-party authentication (e.g., Google, LinkedIn).
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>3.2.</strong> Users are responsible for maintaining the confidentiality of their login credentials and for all activities that occur under their Account.
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>3.3.</strong> Users must promptly notify Usekase of any unauthorized use of their Account or security breaches by contacting <a href="mailto:info@usekase.ai" className="text-primary hover:underline">info@usekase.ai</a>
                  </p>
                </div>
              </section>

              {/* 4. Content and Reports */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">4. Content and Reports</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>4.1.</strong> Usekase generates Reports based on information aggregated from publicly available sources.
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>4.2.</strong> The Content provided in these Reports is for informational purposes only and is not intended as professional advice.
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>4.3. Disclaimer Regarding Content Sourcing and Intellectual Property:</strong>
                  </p>
                  <p className="text-base leading-relaxed pl-6">
                    The information about companies displayed in the system is aggregated from publicly available sources and is provided for informational purposes only. Usekase does not claim ownership over this information, nor does it guarantee its accuracy, completeness, or compliance with any third-party rights. Users acknowledge that Usekase is not liable for any claims, losses, or damages resulting from the use of such information. If any content is believed to infringe upon rights, please contact us at <a href="mailto:info@usekase.ai" className="text-primary hover:underline">info@usekase.ai</a> for review and potential removal.
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>4.4. User-Generated Content Ownership and GDPR Compliance:</strong>
                  </p>
                  <p className="text-base leading-relaxed pl-6">
                    Any content uploaded, submitted, or added by Users to Usekase must be legally owned by the User, and they must have explicit rights to distribute and share such content. Users retain full ownership of any content they add and grant no rights to Usekase beyond what is necessary to provide the Services. Usekase does not claim ownership over user-generated content and does not use such content for any purpose outside the scope of the Services. Users are responsible for ensuring compliance with all applicable data protection laws, including the General Data Protection Regulation (GDPR), and warrant that any uploaded content does not violate the privacy or intellectual property rights of any third party.
                  </p>
                </div>
              </section>

              {/* 5. Use of Services */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">5. Use of Services</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>5.1.</strong> Users agree to use the Services only for lawful purposes and in accordance with these Terms.
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>5.2.</strong> Users shall not:
                  </p>
                  <ul className="space-y-2 list-disc pl-6">
                    <li className="text-base">Use the Services in any manner that could disable, overburden, or impair the website.</li>
                    <li className="text-base">Attempt to gain unauthorized access to any part of the website or Services.</li>
                    <li className="text-base">Use any automated means to access the website or Services without prior authorization.</li>
                  </ul>
                </div>
              </section>

              {/* 6. Payment and Fees */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">6. Payment and Fees</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>6.1.</strong> Certain Services may require payment. Users agree to pay all fees and charges associated with their Account in a timely manner.
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>6.2.</strong> All payments are non-refundable unless otherwise stated.
                  </p>
                </div>
              </section>

              {/* 7. Limitation of Liability */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">7. Limitation of Liability</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>7.1.</strong> To the maximum extent permitted by applicable law, Usekase and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:
                  </p>
                  <ul className="space-y-2 list-disc pl-6">
                    <li className="text-base">Your use or inability to use the Services;</li>
                    <li className="text-base">Any unauthorized access to or use of our servers and/or any personal information stored therein;</li>
                    <li className="text-base">Any interruption or cessation of transmission to or from our Services;</li>
                    <li className="text-base">Any bugs, viruses, trojan horses, or the like that may be transmitted to or through our Services by any third party;</li>
                    <li className="text-base">Any errors or omissions in any content or for any loss or damage incurred as a result of the use of any content posted, emailed, transmitted, or otherwise made available through the Services.</li>
                  </ul>
                </div>
              </section>

              {/* 8. Indemnification */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">8. Indemnification</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>8.1.</strong> Users agree to indemnify and hold harmless Usekase, its affiliates, and their respective officers, directors, employees, and agents from and against any claims, liabilities, damages, losses, and expenses, including without limitation reasonable legal and accounting fees, arising out of or in any way connected with:
                  </p>
                  <ul className="space-y-2 list-disc pl-6">
                    <li className="text-base">User's access to or use of the Services;</li>
                    <li className="text-base">User's violation of these Terms;</li>
                    <li className="text-base">User's violation of any third-party rights, including without limitation any intellectual property rights.</li>
                  </ul>
                </div>
              </section>

              {/* 9. Modifications to Services and Terms */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">9. Modifications to Services and Terms</h2>
                <div className="space-y-3">
                  <p className="text-base leading-relaxed">
                    <strong>9.1.</strong> Usekase reserves the right to modify or discontinue, temporarily or permanently, the Services (or any part thereof) with or without notice.
                  </p>
                  <p className="text-base leading-relaxed">
                    <strong>9.2.</strong> Usekase may amend these Terms at any time by posting the amended terms on its website. It is the User's responsibility to review these Terms periodically. Continued use of the Services after any such changes shall constitute User's consent to such changes.
                  </p>
                </div>
              </section>

              {/* 10. Governing Law */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">10. Governing Law</h2>
                <p className="text-base leading-relaxed">
                  <strong>10.1.</strong> These Terms shall be governed by and construed in accordance with the laws of Singapore, without regard to its conflict of law principles.
                </p>
              </section>

              {/* 11. Contact Information */}
              <section>
                <h2 className="text-2xl font-bold mb-4 text-foreground">11. Contact Information</h2>
                <p className="text-base leading-relaxed mb-4">
                  <strong>11.1.</strong> For any questions about these Terms, please contact Usekase at:
                </p>
                <div className="bg-muted/50 rounded-lg p-4">
                  <div className="flex items-center gap-3">
                    <Mail className="h-5 w-5 text-primary flex-shrink-0" />
                    <a href="mailto:info@usekase.ai" className="text-primary hover:underline text-base">
                      info@usekase.ai
                    </a>
                  </div>
                </div>
              </section>
            </div>
          </motion.div>
        </div>
      </main>

      <UsekaseFooter />
    </div>
  );
}
